package com.example.demo.Entities;
// Generated Jul 13, 2019 12:56:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd1")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private int idHorasDocente;
	private int idSemestre;
	private String nombresDocente;

	public Docente() {
	}

	public Docente(int idDocente, int idHorasDocente, int idSemestre) {
		this.idDocente = idDocente;
		this.idHorasDocente = idHorasDocente;
		this.idSemestre = idSemestre;
	}

	public Docente(int idDocente, int idHorasDocente, int idSemestre, String nombresDocente) {
		this.idDocente = idDocente;
		this.idHorasDocente = idHorasDocente;
		this.idSemestre = idSemestre;
		this.nombresDocente = nombresDocente;
	}

	@Id

	@Column(name = "id_docente", unique = true, nullable = false)
	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@Column(name = "id_horas_docente", nullable = false)
	public int getIdHorasDocente() {
		return this.idHorasDocente;
	}

	public void setIdHorasDocente(int idHorasDocente) {
		this.idHorasDocente = idHorasDocente;
	}

	@Column(name = "id_semestre", nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@Column(name = "nombres_docente", length = 70)
	public String getNombresDocente() {
		return this.nombresDocente;
	}

	public void setNombresDocente(String nombresDocente) {
		this.nombresDocente = nombresDocente;
	}

}
