package com.example.demo.Entities;
// Generated Jul 13, 2019 12:56:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HorasDocente generated by hbm2java
 */
@Entity
@Table(name = "horas_docente", catalog = "cargabd1")
public class HorasDocente implements java.io.Serializable {

	private int idHorasDocente;
	private Integer numeroHoras;

	public HorasDocente() {
	}

	public HorasDocente(int idHorasDocente) {
		this.idHorasDocente = idHorasDocente;
	}

	public HorasDocente(int idHorasDocente, Integer numeroHoras) {
		this.idHorasDocente = idHorasDocente;
		this.numeroHoras = numeroHoras;
	}

	@Id

	@Column(name = "id_horas_docente", unique = true, nullable = false)
	public int getIdHorasDocente() {
		return this.idHorasDocente;
	}

	public void setIdHorasDocente(int idHorasDocente) {
		this.idHorasDocente = idHorasDocente;
	}

	@Column(name = "numero_horas")
	public Integer getNumeroHoras() {
		return this.numeroHoras;
	}

	public void setNumeroHoras(Integer numeroHoras) {
		this.numeroHoras = numeroHoras;
	}

}
