package com.example.demo.Entities;
// Generated Jul 13, 2019 12:56:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd1")
public class Semestre implements java.io.Serializable {

	private int idSemestre;
	private String nombreSemestre;

	public Semestre() {
	}

	public Semestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	public Semestre(int idSemestre, String nombreSemestre) {
		this.idSemestre = idSemestre;
		this.nombreSemestre = nombreSemestre;
	}

	@Id

	@Column(name = "id_semestre", unique = true, nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@Column(name = "nombre_semestre", length = 50)
	public String getNombreSemestre() {
		return this.nombreSemestre;
	}

	public void setNombreSemestre(String nombreSemestre) {
		this.nombreSemestre = nombreSemestre;
	}

}
