package com.example.demo.entities;
// Generated Jul 1, 2019 6:30:26 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private Integer idDocente;
	private Horasdocente horasdocente;
	private Semestre semestre;
	private String nombres;
	private Integer dni;

	public Docente() {
	}

	public Docente(Horasdocente horasdocente, Semestre semestre, String nombres, Integer dni) {
		this.horasdocente = horasdocente;
		this.semestre = semestre;
		this.nombres = nombres;
		this.dni = dni;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDocente", unique = true, nullable = false)
	public Integer getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(Integer idDocente) {
		this.idDocente = idDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idHorasDocente")
	public Horasdocente getHorasdocente() {
		return this.horasdocente;
	}

	public void setHorasdocente(Horasdocente horasdocente) {
		this.horasdocente = horasdocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSemestre")
	public Semestre getSemestre() {
		return this.semestre;
	}

	public void setSemestre(Semestre semestre) {
		this.semestre = semestre;
	}

	@Column(name = "nombres", length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "dni")
	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

}
