package com.example.demo.entities;
// Generated Jul 1, 2019 6:30:26 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Horasdocente generated by hbm2java
 */
@Entity
@Table(name = "horasdocente", catalog = "cargabd")
public class Horasdocente implements java.io.Serializable {

	private int idHorasDocente;
	private int nrohoras;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Horasdocente() {
	}

	public Horasdocente(int idHorasDocente, int nrohoras) {
		this.idHorasDocente = idHorasDocente;
		this.nrohoras = nrohoras;
	}

	public Horasdocente(int idHorasDocente, int nrohoras, Set<Docente> docentes) {
		this.idHorasDocente = idHorasDocente;
		this.nrohoras = nrohoras;
		this.docentes = docentes;
	}

	@Id

	@Column(name = "idHorasDocente", unique = true, nullable = false)
	public int getIdHorasDocente() {
		return this.idHorasDocente;
	}

	public void setIdHorasDocente(int idHorasDocente) {
		this.idHorasDocente = idHorasDocente;
	}

	@Column(name = "nrohoras", nullable = false)
	public int getNrohoras() {
		return this.nrohoras;
	}

	public void setNrohoras(int nrohoras) {
		this.nrohoras = nrohoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horasdocente")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
