package com.example.demo.entities;
// Generated Jul 1, 2019 6:30:26 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semestre generated by hbm2java
 */
@Entity
@Table(name = "semestre", catalog = "cargabd")
public class Semestre implements java.io.Serializable {

	private int idSemestre;
	private String nombreSemestre;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Semestre() {
	}

	public Semestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	public Semestre(int idSemestre, String nombreSemestre, Set<Docente> docentes) {
		this.idSemestre = idSemestre;
		this.nombreSemestre = nombreSemestre;
		this.docentes = docentes;
	}

	@Id

	@Column(name = "idSemestre", unique = true, nullable = false)
	public int getIdSemestre() {
		return this.idSemestre;
	}

	public void setIdSemestre(int idSemestre) {
		this.idSemestre = idSemestre;
	}

	@Column(name = "nombreSemestre", length = 50)
	public String getNombreSemestre() {
		return this.nombreSemestre;
	}

	public void setNombreSemestre(String nombreSemestre) {
		this.nombreSemestre = nombreSemestre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semestre")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
